name: Trigger workflow based on PR Comment

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  keyword_trigger:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger target workflow
        id: parentjobid
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # or use a PAT if needed
        run: |
          echo "${{ github.repository }}"
          PR_NUMBER="${{ github.event.issue.number }}"
          echo "gk_newvar=ThisOriginalVar" >> $GITHUB_OUTPUT
          echo "${PR_NUMBER}"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/pr-trigger.yml/dispatches \
            -d "{\"ref\":\"main\", \"inputs\": {\"myInput\": \"$PR_NUMBER\"}}"
